{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorExternalDevice"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorExternalDevice"}],"platforms":["Linux"],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","role":"symbol","title":"cudaError.cudaErrorExternalDevice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorExternalDevice"}],"roleHeading":"Case","modules":[{"name":"SwiftCU"}],"externalID":"s:7SwiftCU9cudaErrorO0cD14ExternalDeviceyA2CmF"},"abstract":[{"text":"This indicates that an async error has occurred in a device outside of CUDA.","type":"text"},{"text":" ","type":"text"},{"text":"If CUDA was waiting for an external device’s signal before consuming shared data,","type":"text"},{"text":" ","type":"text"},{"text":"the external device signaled an error indicating that the data is not valid for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"consumption. This leaves the process in an inconsistent state and any further CUDA"},{"type":"text","text":" "},{"type":"text","text":"work will return the same error. To continue using CUDA, the process must be"},{"type":"text","text":" "},{"type":"text","text":"terminated and relaunched."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftCU\/documentation\/SwiftCU","doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError"]]},"variants":[{"paths":["\/documentation\/swiftcu\/cudaerror\/cudaerrorexternaldevice"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://SwiftCU/documentation/SwiftCU/cudaError/cudaErrorExternalDevice":{"url":"\/documentation\/swiftcu\/cudaerror\/cudaerrorexternaldevice","title":"cudaError.cudaErrorExternalDevice","identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorExternalDevice","abstract":[{"type":"text","text":"This indicates that an async error has occurred in a device outside of CUDA."},{"type":"text","text":" "},{"type":"text","text":"If CUDA was waiting for an external device’s signal before consuming shared data,"},{"type":"text","text":" "},{"type":"text","text":"the external device signaled an error indicating that the data is not valid for"},{"type":"text","text":" "},{"type":"text","text":"consumption. This leaves the process in an inconsistent state and any further CUDA"},{"type":"text","text":" "},{"type":"text","text":"work will return the same error. To continue using CUDA, the process must be"},{"type":"text","text":" "},{"type":"text","text":"terminated and relaunched."}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorExternalDevice"}]},"doc://SwiftCU/documentation/SwiftCU/cudaError":{"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaError"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"cudaError"}],"title":"cudaError","url":"\/documentation\/swiftcu\/cudaerror","role":"symbol"},"doc://SwiftCU/documentation/SwiftCU":{"role":"collection","identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU","kind":"symbol","title":"SwiftCU","url":"\/documentation\/swiftcu","abstract":[],"type":"topic"}}}