{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorExternalDevice","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorExternalDevice"}]}]}],"abstract":[{"type":"text","text":"This indicates that an async error has occurred in a device outside of CUDA."},{"type":"text","text":" "},{"type":"text","text":"If CUDA was waiting for an external device’s signal before consuming shared data,"},{"type":"text","text":" "},{"type":"text","text":"the external device signaled an error indicating that the data is not valid for"},{"type":"text","text":" "},{"type":"text","text":"consumption. This leaves the process in an inconsistent state and any further CUDA"},{"type":"text","text":" "},{"type":"text","text":"work will return the same error. To continue using CUDA, the process must be"},{"type":"text","text":" "},{"type":"text","text":"terminated and relaunched."}],"metadata":{"symbolKind":"case","externalID":"s:7SwiftCU9cudaErrorO0cD14ExternalDeviceyA2CmF","title":"cudaError.cudaErrorExternalDevice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorExternalDevice"}],"modules":[{"name":"SwiftCU"}],"role":"symbol","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/SwiftCU\/documentation\/SwiftCU","doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftcu\/cudaerror\/cudaerrorexternaldevice"]}],"sections":[],"references":{"doc://SwiftCU/documentation/SwiftCU/cudaError/cudaErrorExternalDevice":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorExternalDevice"}],"title":"cudaError.cudaErrorExternalDevice","url":"\/documentation\/swiftcu\/cudaerror\/cudaerrorexternaldevice","abstract":[{"text":"This indicates that an async error has occurred in a device outside of CUDA.","type":"text"},{"text":" ","type":"text"},{"text":"If CUDA was waiting for an external device’s signal before consuming shared data,","type":"text"},{"text":" ","type":"text"},{"text":"the external device signaled an error indicating that the data is not valid for","type":"text"},{"text":" ","type":"text"},{"text":"consumption. This leaves the process in an inconsistent state and any further CUDA","type":"text"},{"text":" ","type":"text"},{"text":"work will return the same error. To continue using CUDA, the process must be","type":"text"},{"text":" ","type":"text"},{"text":"terminated and relaunched.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorExternalDevice"},"doc://SwiftCU/documentation/SwiftCU":{"identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU","title":"SwiftCU","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/swiftcu","kind":"symbol"},"doc://SwiftCU/documentation/SwiftCU/cudaError":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cudaError","kind":"identifier"}],"url":"\/documentation\/swiftcu\/cudaerror","kind":"symbol","navigatorTitle":[{"text":"cudaError","kind":"identifier"}],"identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError","title":"cudaError","abstract":[],"type":"topic"}}}